# Generated by Django 4.2.15 on 2025-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-time_create'], name='jobs_public_time_cr_888d00_idx'),
        ),
    ]
