# Generated by Django 4.2.15 on 2025-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_publication_options_publication_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
