# Generated by Django 4.2.15 on 2025-01-04 17:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_publication_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('is_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.BooleanField(choices=[(0, 'Archive'), (1, 'Published')], default=1),
        ),
    ]
