# Generated by Django 4.2.15 on 2025-01-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_company_alter_publication_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.company'),
        ),
    ]
